//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBotWebApp.Services.Resourses
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBotWebApp.Services.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter /status - to get status of your target vessel and port.
        ///
        ///🛳🔄 Enter /refresh_ship to get ship schedule.
        ///To re-set target vessel, just enter another name.
        ///
        ///Enter /order_descending to change print order to descending.
        ///Descending - Nearest date is last.
        ///
        ///Enter /order_ascending to change print order to descending.
        ///Ascending - Nearest date is first.
        ///
        ///Schedule is printed in format where: 
        ///LOCA - vessel call location name
        ///CODE - UN/LOCODE - SMDG facility code
        ///ARRI / DEPA - date and time in form [rest of string was truncated]&quot;;.
        /// </summary>
        public static string command_help {
            get {
                return ResourceManager.GetString("command_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛳🔄 Enter /refresh_ship to get ship schedule.
        ///To re-set target vessel, just enter another name..
        /// </summary>
        public static string command_refresh_ship {
            get {
                return ResourceManager.GetString("command_refresh_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Schedule will be printed in &lt;b&gt;descending order&lt;/b&gt; ⬆️ &lt;i&gt;(from bottom to top)&lt;/i&gt;.
        ////order_ascending to change order to ascending (from top to bottom)..
        /// </summary>
        public static string print_order_ascending_false {
            get {
                return ResourceManager.GetString("print_order_ascending_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Schedule will be printed in &lt;b&gt;ascending order&lt;/b&gt; ⬇️ &lt;i&gt;(from top to bottom)&lt;/i&gt;.
        ////order_descending to change order to descending (from bottom to top)..
        /// </summary>
        public static string print_order_ascending_true {
            get {
                return ResourceManager.GetString("print_order_ascending_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Can not find a matching name. ❌.
        /// </summary>
        public static string search_results_none {
            get {
                return ResourceManager.GetString("search_results_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found several results:.
        /// </summary>
        public static string search_results_several {
            get {
                return ResourceManager.GetString("search_results_several", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match found:.
        /// </summary>
        public static string search_results_single {
            get {
                return ResourceManager.GetString("search_results_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛳❌Your target vessel is missing.
        ///Please enter vessel name to set it up..
        /// </summary>
        public static string target_vessel_null {
            get {
                return ResourceManager.GetString("target_vessel_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛳✅ Your target vessel is -.
        /// </summary>
        public static string target_vessel_set {
            get {
                return ResourceManager.GetString("target_vessel_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Maersk Schedule Bot!
        ///You can get vessels schedule for vessels that sail A.P. Moller-Maersk A/S routes.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
